name: Build Docker Images
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the API Docker image
      run: docker build --pull -t cequel-space-api api --tag cequel-space-api:$(date +%s)
    - name: Build the APP Docker image
      run: docker build --pull -t cequel-space-app app --tag cequel-space-app:$(date +%s)
