name: Browser Client - CI

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:

  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build the API Docker image
        run: docker build --pull -t cequel-space-api api --tag cequel-space-api

      - name: Build the APP Docker image
        run: docker build --pull -t cequel-space-app app --tag cequel-space-app

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u benvoss --password-stdin

      - name: Push image
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest

          echo VERSION=$VERSION

          docker tag cequel-space-api benvoss/cequel-space:api-$VERSION
          docker push benvoss/cequel-space:api-$VERSION

          docker tag cequel-space-app benvoss/cequel-space:app-$VERSION
          docker push benvoss/cequel-space:app-$VERSION