apiVersion: v1
kind: Service
metadata:
  name: cequel-space-app
  labels:
    component: cequel-space-app
spec:
  ports:
    - port: 80
      name: http
      targetPort: 80
  selector:
    component: cequel-space-app
